# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/data401-nlp',
                'doc_host': 'https://su-dataAI.github.io',
                'git_url': 'https://github.com/su-dataAI/data401-nlp',
                'lib_path': 'data401_nlp'},
  'syms': {'data401_nlp.core': {'data401_nlp.core.foo': ('core.html#foo', 'data401_nlp/core.py')}}}
