"""Tests to verify the package works across different platforms (Colab, Deepnote, Local)"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/99_platform_test.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/99_platform_test.ipynb 2
import sys
import importlib.util
import data401_nlp
import data401_nlp.helpers.env
import data401_nlp.helpers.llm
import data401_nlp.helpers.submit
import data401_nlp.helpers.spacy
from .. import __version__
from ..helpers.env import load_env
from ..helpers.spacy import list_installed_models
