"""This helper centralizes **environment-specific setup** for notebooks that rely on external APIs (e.g. OpenAI, Anthropic)."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/helpers/00_env.ipynb.

# %% auto #0
__all__ = ['load_env']

# %% ../../nbs/helpers/00_env.ipynb #db04faa5
import os

# %% ../../nbs/helpers/00_env.ipynb #4eb39b10
import os
from pathlib import Path

def load_env():
    """
    Load API keys in a platform-aware way.

    This function attempts to populate environment variables required by
    downstream LLM helpers. The strategy depends on where the notebook
    is running:

    - **Google Colab**: read keys from `google.colab.userdata`
    - **Local development**: load keys from a `.env` file if present
    - **Hosted environments** (e.g. Deepnote / Solveit): assume keys are already injected

    The function does not validate keys or make API calls.

    Returns
    -------
    str
        One of {"colab", "dotenv", "external"}, indicating which environment
        was detected.
    """
    try:
        import google.colab
        from google.colab import userdata

        os.environ.setdefault("ANTHROPIC_API_KEY", userdata.get("ANTHROPIC_API_KEY"))
        os.environ.setdefault("OPENAI_API_KEY", userdata.get("OPENAI_API_KEY"))
        os.environ.setdefault("SUBMIT_API_KEY", userdata.get("SUBMIT_API_KEY"))
        return "colab"

    except ImportError:
        pass

# --- Local dev: bounded upward search for .env ---
    cwd = Path.cwd().resolve()

    for parent in [cwd, *cwd.parents]:
        env_file = parent / ".env"
        if env_file.exists():
            from dotenv import load_dotenv
            load_dotenv(env_file)
            return "dotenv"

        # stop if we clearly hit project root
        if (
            (parent / ".git").exists()
            or (parent / "pyproject.toml").exists()
            or (parent / "data401_nlp").exists()
        ):
            break

    # Deepnote / other hosted env
    return "external"

